# -*- coding: utf-8 -*-
"""reading_email.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiDuv0HWtMDTe9r9TuP1TiZBVE2N6VXa

# Collecting Email Addresses
"""



from google.colab import drive
drive.mount('/content/drive')

# needed imports
import pandas as pd
from google.colab import files
import re

# reading content from .txt file
with open('/content/drive/My Drive/data.rtf', 'r') as f:
    data = f.read()

# printing the content to see if reading is successful

print(data)

email_regex_pattern = re.compile(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}')

addresses = email_regex_pattern.findall(data)

print("Extracted email addresses:")
for address in addresses:
    print(address)

output_filename = "extracted_emails.txt"
with open(output_filename, 'w') as output_file:
    for address in addresses:
        output_file.write(address + '\n')

files.download(output_filename)